// web/src/routes/nav-bar.svelte
<script lang="ts">
	import { page } from '$app/state';
	import Button from '$lib/components/ui/button/button.svelte';
	import * as Sheet from '$lib/components/ui/sheet';
	import { cn } from '$lib/utils';
	import { Menu, Search } from 'lucide-svelte';

	const links = [
		{
			label: 'Home',
			link: '/'
		},
		{
			label: 'Catalog',
			link: '/catalog'
		},
		{
			label: 'Genres',
			link: '/genres'
		},
		{
			label: 'My List',
			link: '/my-list'
		}
	];

	let isSheetOpen = $state(false);
</script>

<header
	class="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur-md supports-[backdrop-filter]:bg-background/60"
>
	<div class="container mx-auto p-4">
		<div class="flex items-center justify-between">
			<div class="flex items-center space-x-8">
				<h1 class="tracking-light font-serif text-3xl font-extrabold text-primary uppercase">
					<a href="/">Aniways</a>
				</h1>

				<nav class="hidden space-x-6 lg:flex">
					{#each links as link (link.link)}
						<a
							href={link.link}
							class={cn(
								'font-medium text-muted-foreground transition-colors hover:text-primary',
								page.url.pathname === link.link && 'text-foreground'
							)}
						>
							{link.label}
						</a>
					{/each}
				</nav>
			</div>

			<div class="flex items-center gap-4">
				<Button variant="outline" class="lg:hidden" onclick={() => (isSheetOpen = true)}>
					<Menu class="h-5 w-5" />
					<span class="sr-only">Menu</span>
				</Button>
				<Button
					variant="outline"
					class="hidden w-64 items-center justify-start space-x-2 border-muted-foreground/20 bg-transparent text-muted-foreground hover:border-primary/50 lg:flex"
				>
					<Search class="h-4 w-4" />
					<span>Search anime...</span>
					<kbd
						class="pointer-events-none ml-auto inline-flex h-5 items-center gap-1 rounded border bg-muted px-1.5 font-mono text-[10px] font-medium text-muted-foreground opacity-100 select-none"
					>
						<span class="text-xs">⌘</span>K
					</kbd>
				</Button>

				<Button href="/login" variant="outline" class="hidden lg:inline-flex">Sign In</Button>
				<Button href="/register" class="hidden lg:inline-flex">Register</Button>
			</div>
		</div>
	</div>
</header>

<Sheet.Root bind:open={isSheetOpen}>
	<Sheet.Content side="right">
		<Sheet.Header>
			<Sheet.Title>Menu</Sheet.Title>
		</Sheet.Header>
		<div class="flex flex-col gap-2 px-4">
			{#each links as link (link.link)}
				<a
					href={link.link}
					class={cn(
						'font-medium text-muted-foreground transition-colors hover:text-primary',
						page.url.pathname === link.link && 'text-foreground'
					)}
				>
					{link.label}
				</a>
			{/each}
		</div>
		<div class="flex flex-col gap-2 px-4">
			<Button variant="outline" class="w-full">
				<Search class="h-4 w-4" />
				<span>Search anime...</span>
			</Button>
			<Button href="/login" variant="outline" class="w-full">Sign In</Button>
			<Button href="/register" class="w-full">Register</Button>
		</div>
	</Sheet.Content>
</Sheet.Root>

// web/app/components/nav-bar.vue
<script setup lang="ts">
import { Search, Menu } from 'lucide-vue-next';

const items = [
    { label: 'Home', to: '/' },
    { label: 'Catalog', to: '/catalog' },
    { label: 'Season', to: '/season' },
    { label: 'Top', to: '/top' },
];

const route = useRoute();
const mobileOpen = ref(false);
const isActive = (to: string) => to === route.path;
const openSearch = () => {
    mobileOpen.value = true;
};

watch(
    () => route.path,
    () => {
        mobileOpen.value = false;
    },
);
</script>
<template>
    <nav class="sticky top-0 z-50 border-b bg-transparent">
        <div
            class="mx-auto flex w-full max-w-[1640px] items-center gap-4 px-4 py-3 lg:gap-8 lg:px-12 lg:py-4"
        >
            <Sheet v-model:open="mobileOpen">
                <SheetTrigger as-child>
                    <Button variant="outline" size="icon" class="lg:hidden">
                        <Menu class="size-5" />
                        <span class="sr-only">Open menu</span>
                    </Button>
                </SheetTrigger>

                <NuxtLink
                    class="font-bungee text-2xl font-bold lg:text-3xl"
                    to="/"
                >
                    ANIWAYS
                </NuxtLink>

                <ul class="mx-1 hidden gap-4 lg:flex">
                    <li v-for="item in items" :key="item.label">
                        <NuxtLink
                            :to="item.to"
                            :data-active="isActive(item.to)"
                            class="text-muted-foreground hover:text-foreground data-[active=true]:text-foreground"
                        >
                            {{ item.label }}
                        </NuxtLink>
                    </li>
                </ul>

                <div class="relative ml-auto hidden w-full lg:block">
                    <label for="search" class="sr-only">Search</label>
                    <Search
                        class="text-muted-foreground pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2"
                    />
                    <Input
                        id="search"
                        placeholder="Search"
                        class="bg-muted/50 w-full pl-10"
                    />
                </div>

                <div class="hidden items-center gap-3 lg:flex">
                    <Button variant="secondary" as-child>
                        <NuxtLink to="/login">Login</NuxtLink>
                    </Button>
                    <Button as-child>
                        <NuxtLink to="/signup">Get Started</NuxtLink>
                    </Button>
                </div>

                <Button
                    variant="ghost"
                    size="icon"
                    class="ml-auto lg:hidden"
                    aria-label="Search"
                    @click="openSearch"
                >
                    <Search class="size-5" />
                </Button>

                <SheetContent side="left" class="w-80 p-6">
                    <SheetHeader class="mb-4">
                        <SheetTitle class="font-bungee text-2xl"
                            >ANIWAYS</SheetTitle
                        >
                    </SheetHeader>

                    <div class="relative mb-4">
                        <label for="m-search" class="sr-only">Search</label>
                        <Search
                            class="text-muted-foreground pointer-events-none absolute top-1/2 left-3 size-4 -translate-y-1/2"
                        />
                        <Input
                            id="m-search"
                            placeholder="Search"
                            class="bg-muted/50 w-full pl-10"
                        />
                    </div>

                    <nav class="grid gap-1">
                        <SheetClose
                            v-for="item in items"
                            :key="item.label"
                            as-child
                        >
                            <NuxtLink
                                :to="item.to"
                                :data-active="isActive(item.to)"
                                class="text-muted-foreground hover:bg-muted/60 hover:text-foreground data-[active=true]:bg-muted data-[active=true]:text-foreground block rounded-md px-3 py-2 text-sm"
                            >
                                {{ item.label }}
                            </NuxtLink>
                        </SheetClose>
                    </nav>

                    <div class="mt-6 flex gap-2">
                        <SheetClose as-child>
                            <Button variant="secondary" class="flex-1" as-child>
                                <NuxtLink to="/login">Login</NuxtLink>
                            </Button>
                        </SheetClose>
                        <SheetClose as-child>
                            <Button class="flex-1" as-child>
                                <NuxtLink to="/signup">Get Started</NuxtLink>
                            </Button>
                        </SheetClose>
                    </div>
                </SheetContent>
            </Sheet>
        </div>
    </nav>
</template>
